### PR TITLE
feature/implement-get-events

### PR DESCRIPTION
**Pull request by tohuynh**
Just improving the create fake data function from PR [#9](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/pull/9) based on feedback and moving said function to `example` repo instead.

I decided to make `result_status` always `In Progress` because randomly choosing a value could lead to an illogical history of the matter's statuses.

Do I need to update the requirements.txt for `cdp-backend` version as well?

### CODE REVIEW

**Review by JacksonMaxfield — APPROVED** [review]
This looks so good. Feel free to merge whenever, I will patch the black / flake8 conflicts in upstream cookiecutter and passthrough to here this weekend.

Out of curiousity could you post two of the examples that it generates as comments to this PR?

**Comment by tohuynh** [comment]
> Out of curiousity could you post two of the examples that it generates as comments to this PR?

For sure, I need to publish cdp-backend and add that version to the requirements.txt in order to use `cdp_backend.database.constants`?

**Comment by JacksonMaxfield** [comment]
> > Out of curiousity could you post two of the examples that it generates as comments to this PR?
> 
> For sure, I need to publish cdp-backend and add that version to the requirements.txt in order to use `cdp_backend.database.constants`?

Woops. Yea. Should just be a `bump2version dev_release` then push to `main`. If you don't have permissions let me know...

**Comment by tohuynh** [comment]
> Woops. Yea. Should just be a `bump2version dev_release` then push to `main`. If you don't have permissions let me know...

Do all of this while in local main branch?

**Comment by JacksonMaxfield** [comment]
Yep: https://github.com/CouncilDataProject/cdp-backend/blob/main/CONTRIBUTING.md#deploying

**Comment by tohuynh** [comment]
It's not letting me git push. It says  I need 1 approving review

**Comment by JacksonMaxfield** [comment]
Hmmm can you try with `-f` / force push?

**Comment by tohuynh** [comment]
> Out of curiousity could you post two of the examples that it generates as comments to this PR?

Here's a JSON file of two events: https://gist.github.com/tohuynh/0f5a21398759c562ff59bd7e9c7da9d6

I used jsonpickle to convert the objects to JSON.

**Pull request merged**
